### ISSUE TITLE
make inlines static

### ISSUE THREAD

**Issue by nerdralph** [nerdralph/usbasp#2]
inline functions in C11 can result in undefined symbols if not static and not declared extern in one translation unit.
https://gustedt.wordpress.com/2010/11/29/myth-and-reality-about-inline-in-c99/

**Comment by MCUdude** [comment]
I did try to load the compiled binary to my USBISP hardware after adding `static` to the `inline void spiHWenable()` function. However, nothing happens! The newly flashed USBISP programmer does not show up under device manager, and the on-board LED doesn't light up after programming. When loading the m88.hex file you just provided, everything works perfectly.

I did try to compile with avr-gcc 5.4.0 and 7.3.0. Same result with both compilers.

**Comment by MCUdude** [comment]
Commit eb9045a did the trick. It's now compiling, and the binary that's generated works too! Thanks!

Would you like to quickly explain why this was an issue that I got that you didn't?

**Comment by MCUdude** [comment]
As I wrote on Github, it's working now!

BTW I see you forked Bill Perry's fork rather than the official firmware. What improvements did his fork bring over the official one?

Hans

**Comment by nerdralph** [comment]
> 
> 
> Commit [eb9045a](https://github.com/nerdralph/usbasp/commit/eb9045a0dd74221b5872800a8acc758ef8d17eb2) did the trick. It's now compiling, and the binary that's generated works too! Thanks!
> 
> Would you like to quickly explain why this was an issue that I got that you didn't?

It'll be hard to explain until I can reproduce it myself.

**Comment by nerdralph** [comment]
There wasn't much different with Bill's fork that I could notice.  He refreshed V-USB, and bumped the firmware version from 1.04 to 1.05.

**Comment by MCUdude** [comment]
>>Commit eb9045a did the trick. It's now compiling, and the binary that's generated works too! Thanks!
Would you like to quickly explain why this was an issue that I got that you didn't?



> There wasn't much different with Bill's fork that I could notice. He refreshed V-USB, and bumped the firmware version from 1.04 to 1.05.

I'll assume this is true for bperrybap's for as well, which Bill Perry's fork is based on?

**Comment by nerdralph** [comment]
> 
> 
> > There wasn't much different with Bill's fork that I could notice. He refreshed V-USB, and bumped the firmware version from 1.04 to 1.05.
> 
> I'll assume this is true for bperrybap's for as well, which Bill Perry's fork is based on?

Isn't github.com/bperrybap/ Bill Perry's account?

**Comment by nerdralph** [comment]
I was able to duplicate the undefined spiHWenable error with avr-gcc 7.3.0 when it is just inline (not static).  I don't see much point digging any further into it.  I will try to setup CI for the repo building with both avr-gcc 5.4.0 and 7.3.0 to help avoid more bugs like this in the future.

**Comment by nerdralph** [comment]
Closing since it's fixed now.

**Comment by MCUdude** [comment]
>>>There wasn't much different with Bill's fork that I could notice. He refreshed V-USB, and bumped the firmware version from 1.04 to 1.05.

>>I'll assume this is true for bperrybap's for as well, which Bill Perry's fork is based on?

>Isn't github.com/bperrybap/ Bill Perry's account?

Sorry, I mixed Bill Perry and PeterVH. The question was supposed to be, what's the difference between the official firmware and the one from PeterVH's repo?
