### ISSUE TITLE
UART Support

### ISSUE THREAD

**Issue by dioannidis** [nerdralph/usbasp#9]
Hi,

  AFAIU the original schematic has provision to support uart, so I implemented it to your USBasp firmware based on the work of  @akrasuski1 ( https://github.com/akrasuski1/usbasp-uart ). I used a different ring buffer and changed the read and write logic but the usb calls signatures is the same.
  
  Based on my tests, with the 12MHz crystal, a baud rate of 19200 can be used reliably using control trasfers. At 38400, 57600 and 115200 baud rates, if the data stream are short ( so it can be stored in the 128 bytes internal buffer ) or sended in 150 bytes "packets" with a 20 - 30 ms interval, it works well ~~also~~. If one replaces the crystal with a 20MHz then a 38400 baud rate can be used reliable also. For the 57600 and 115200 baud rates the data stream length ~~the~~ issue ~~is the same~~ remains.

Of course, this addition can not be used in a atmega48.

What do you think ?

**Comment by nerdralph** [comment]
Since it doesn't conform to the USB CDC spec, I think it is mainly a novelty.  In addition, I've been busy with other projects lately and will be spending minimal time on open-source work over the coming weeks.
